// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uujulyagyetiyfgwdoun.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1anVseWFneWV0aXlmZ3dkb3VuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTM5MjMsImV4cCI6MjA2NjE4OTkyM30.s2iet7p2PQZvb8se8Pba8LjY8hQzs8IH0lOR9fknuAs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);